In [43]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [44]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [45]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [46]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [47]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [48]:
dependent=dataset['charges']

In [49]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5]
}

grid = GridSearchCV(
    XGBRegressor(random_state=0),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    cv=5
)

grid.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=True, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bin=None,
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1], 'max_depth': [3, 5],
                         'n_estimators': [50, 100]},
             verbose=3)

In [54]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}:

In [55]:
table=pd.DataFrame.from_dict(re)

In [56]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016946,0.001604,0.002408,0.000220,0.05,3,50,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",0.839511,0.803607,0.869860,0.846438,0.791456,0.830174,0.028745,3
1,0.030525,0.002827,0.002594,0.000126,0.05,3,100,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",0.839585,0.814579,0.872065,0.849151,0.798831,0.834842,0.025769,1
2,0.029116,0.002554,0.003074,0.000606,0.05,5,50,"{'learning_rate': 0.05, 'max_depth': 5, 'n_est...",0.819257,0.796323,0.865001,0.841783,0.780847,0.820642,0.030304,5
3,0.050617,0.001312,0.003187,0.000566,0.05,5,100,"{'learning_rate': 0.05, 'max_depth': 5, 'n_est...",0.809914,0.798124,0.864393,0.835448,0.777979,0.817172,0.030051,6
4,0.018563,0.000488,0.002843,0.000691,0.10,3,50,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.838866,0.814449,0.871541,0.849654,0.799023,0.834707,0.025617,2
5,0.030545,0.001463,0.002642,0.000442,0.10,3,100,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.831955,0.807134,0.865352,0.837512,0.788655,0.826121,0.026333,4
6,0.027154,0.002029,0.001860,0.000257,0.10,5,50,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.809675,0.792502,0.863999,0.831472,0.781213,0.815772,0.029480,7
7,0.035968,0.004150,0.001751,0.000306,0.10,5,100,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.792676,0.758969,0.856416,0.810574,0.761795,0.796086,0.035819,8

In [57]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 21
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [58]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])#␣
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[16224.029]