In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [7]:
dependent=dataset['charges']

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMRegressor

param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5],
    'num_leaves': [15, 31]
}

grid = GridSearchCV(
    LGBMRegressor(random_state=0, verbosity=-1),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    cv=5
)

grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5, estimator=LGBMRegressor(random_state=0, verbosity=-1),
             n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1], 'max_depth': [3, 5],
                         'n_estimators': [50, 100], 'num_leaves': [15, 31]},
             verbose=3)

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100, 'num_leaves': 15}:

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,param_num_leaves,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,3.118938,0.037030,0.004248,0.000395,0.05,3,50,15,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",0.819559,0.804489,0.868060,0.852862,0.788047,0.826603,0.029777,7
1,3.119958,0.103586,0.003670,0.001184,0.05,3,50,31,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",0.819559,0.804489,0.868060,0.852862,0.788047,0.826603,0.029777,7
2,3.321481,0.064603,0.002571,0.000223,0.05,3,100,15,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",0.823783,0.813560,0.868608,0.856630,0.799058,0.832328,0.026226,1
3,0.898237,1.240716,0.002226,0.000046,0.05,3,100,31,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",0.823783,0.813560,0.868608,0.856630,0.799058,0.832328,0.026226,1
4,0.285428,0.000916,0.002222,0.000088,0.05,5,50,15,"{'learning_rate': 0.05, 'max_depth': 5, 'n_est...",0.815935,0.800354,0.861159,0.851342,0.789444,0.823647,0.028093,13
5,0.222215,0.021611,0.002218,0.000083,0.05,5,50,31,"{'learning_rate': 0.05, 'max_depth': 5, 'n_est...",0.814072,0.801123,0.859763,0.849426,0.788902,0.822657,0.027460,14
6,0.280256,0.008623,0.002850,0.000391,0.05,5,100,15,"{'learning_rate': 0.05, 'max_depth': 5, 'n_est...",0.817847,0.804121,0.862241,0.850979,0.794759,0.825989,0.026300,9
7,0.303819,0.004914,0.002378,0.000093,0.05,5,100,31,"{'learning_rate': 0.05, 'max_depth': 5, 'n_est...",0.816381,0.806169,0.861257,0.850481,0.794353,0.825728,0.025804,11
8,0.065736,0.002612,0.002076,0.000076,0.10,3,50,15,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.822391,0.813223,0.869095,0.855478,0.800536,0.832145,0.025931,3
9,0.067985,0.000590,0.002157,0.000088,0.10,3,50,31,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.822391,0.813223,0.869095,0.855478,0.800536,0.832145,0.025931,3
10,0.151646,0.010651,0.002314,0.000130,0.10,3,100,15,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.818738,0.807760,0.863466,0.851871,0.797153,0.827798,0.025591,5
11,0.145420,0.005113,0.002200,0.000129,0.10,3,100,31,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.818738,0.807760,0.863466,0.851871,0.797153,0.827798,0.025591,5
12,0.148510,0.006962,0.002248,0.000064,0.10,5,50,15,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.816705,0.806389,0.860157,0.851718,0.794260,0.825846,0.025715,10
13,0.156745,0.011310,0.002188,0.000075,0.10,5,50,31,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.816164,0.804883,0.861522,0.850072,0.794337,0.825396,0.026018,12
14,0.199415,0.005919,0.002277,0.000100,0.10,5,100,15,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.807840,0.791796,0.854282,0.844859,0.789305,0.817616,0.027020,16
15,0.184875,0.010691,0.002126,0.000032,0.10,5,100,31,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.813039,0.792982,0.854461,0.844819,0.789140,0.818888,0.026563,15

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 26
BMI: 32
Children: 3
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])#␣
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[18181.20642592]