In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [23]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [24]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [25]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [26]:
dependent=dataset['charges']

In [27]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [50, 100, 200],
    'criterion': ['squared_error', 'absolute_error', 'friedman_mse'],
    'max_features': [1.0, 'sqrt', 'log2'],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10]
}

grid = GridSearchCV(
    RandomForestRegressor(random_state=0),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1,
    cv=5
)

grid.fit(independent, dependent)

Fitting 5 folds for each of 324 candidates, totalling 1620 fits

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=0), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_depth': [None, 5, 10, 20],
                         'max_features': [1.0, 'sqrt', 'log2'],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [29]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
#grid_predictions = grid.predict(X_test)
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_depth': 5, 'max_features': 1.0, 'min_samples_split': 10, 'n_estimators': 100}:

In [30]:
table=pd.DataFrame.from_dict(re)

In [31]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.412463,0.024010,0.018591,0.002244,squared_error,None,1.0,2,50,"{'criterion': 'squared_error', 'max_depth': No...",0.852305,0.766063,0.851718,0.818305,0.834627,0.824604,0.031843,316
1,0.832221,0.033150,0.038335,0.003241,squared_error,None,1.0,2,100,"{'criterion': 'squared_error', 'max_depth': No...",0.848597,0.766514,0.854162,0.821930,0.833573,0.824955,0.031339,314
2,1.691154,0.042044,0.074114,0.020177,squared_error,None,1.0,2,200,"{'criterion': 'squared_error', 'max_depth': No...",0.848867,0.768586,0.853477,0.820938,0.834847,0.825343,0.030581,310
3,0.355376,0.025101,0.017898,0.003224,squared_error,None,1.0,5,50,"{'criterion': 'squared_error', 'max_depth': No...",0.863155,0.774977,0.862752,0.826216,0.847311,0.834882,0.032846,239
4,0.719188,0.038483,0.028583,0.006008,squared_error,None,1.0,5,100,"{'criterion': 'squared_error', 'max_depth': No...",0.860085,0.775806,0.863934,0.828286,0.845523,0.834727,0.032018,249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,0.540018,0.048096,0.028472,0.004612,friedman_mse,20,log2,5,100,"{'criterion': 'friedman_mse', 'max_depth': 20,...",0.867952,0.791253,0.866659,0.835976,0.848037,0.841975,0.028034,191
320,1.104354,0.030723,0.046905,0.001660,friedman_mse,20,log2,5,200,"{'criterion': 'friedman_mse', 'max_depth': 20,...",0.869054,0.791418,0.870326,0.835312,0.848590,0.842940,0.028902,177
321,0.250789,0.021074,0.015423,0.000980,friedman_mse,20,log2,10,50,"{'criterion': 'friedman_mse', 'max_depth': 20,...",0.870916,0.793343,0.873573,0.839780,0.849504,0.845423,0.028993,77
322,0.475563,0.010919,0.022608,0.001447,friedman_mse,20,log2,10,100,"{'criterion': 'friedman_mse', 'max_depth': 20,...",0.869883,0.795400,0.872033,0.837907,0.853544,0.845753,0.028038,64
323,0.835655,0.023980,0.043964,0.003209,friedman_mse,20,log2,10,200,"{'criterion': 'friedman_mse', 'max_depth': 20,...",0.871391,0.796687,0.872939,0.838930,0.854683,0.846926,0.028012,42

In [32]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 25
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [33]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[17991.62656188]

C:\Users\arunk\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(